development:
  adapter: postgresql
  database: gym_app_development
  pool: 5
  timeout: 5000
  username: newuser
  password: password

production:
  adapter: postgresql
  database: gym_app_production
  pool: 5
  timeout: 5000
